# Generated by Django 4.0.1 on 2022-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_comment_author_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='importance',
            field=models.CharField(choices=[('green', 'I can work, but its bothersome'), ('orange', 'This has created extra steps in order for me to work'), ('red', 'I cannot work at all')], default='green', max_length=50),
        ),
    ]
