# Generated by Django 4.0.1 on 2022-02-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Ticket reviewed, wait for an IT specialist to respond.'), ('progress', 'Ticket resolution in progress.'), ('closed', 'Ticket closed.')], default='new', max_length=50),
        ),
    ]
